(function() {
  'use strict';

  var path     = require( 'path' ),
      nunjucks = require( 'nunjucks' ),
      Promise  = require( 'bluebird' ),
      rootPath = path.normalize(__dirname + '/../../');

  module.exports = {
    authorize         : require( './authorize'),
    clusterService    : require( './cluster' ),
    config            : require( './config' ),
    ContactUs         : require('../model/ContactUs'),
    Comment           : require('../model/Comment'),
    createSendToken   : require( './createSendToken' ),
    postSubscription  : require('./postSubscription'),
    facebookAuth      : require( './facebookAuth' ),
    googleAuth        : require( './googleAuth' ),
    Mood              : require('../model/Mood'),
    MoodCount         : require('../model/MoodCount'),
    User              : require( '../model/User' ),
    Post              : require( '../model/Post'),
    PostCarousel      : require('../model/PostCarousel'),
    PostHeadline      : require('../model/PostHeadline'),
    PostSubscription  : require('../model/PostSubscription'),
    PostTopTen        : require('../model/PostTopTen'),
    mongoDB           : require( '../configuration/mongodb' ),
    xPoweredBy        : require( './xPoweredBy' ),
    bodyParser        : require( 'body-parser' ),
    chalk             : require( 'chalk' ),
    cluster           : require( 'cluster' ),
    compression       : require( 'compression' ),
    express           : require( 'express' ),
    expressSession    : require( 'express-session' ),
    favicon           : require( 'serve-favicon' ),
    fs                : require('fs'),
    jwt               : require( 'jwt-simple' ),
    LocalStrategy     : require( 'passport-local' ).Strategy,
    logger            : require( 'morgan' ),
    methodOverride    : require( 'method-override' ),
    moment            : require( 'moment' ),
    mongoose          : require( 'mongoose' ),
    multer            : require( 'multer' ),
    nodemailer        : require('nodemailer'),
    numCPUs           : require( 'os' ).cpus().length,
    nunjucks          : require( 'nunjucks' ),
    nunjucksEnv       : new nunjucks.Environment(new nunjucks.FileSystemLoader(path.join(rootPath, 'views'))),
    ObjectId          : require('mongodb').ObjectID,
    path              : require('path'),
    passport          : require( 'passport' ),
    Promise           : require( 'bluebird' ),
    qs                : require( 'querystring' ),
    request           : require( 'request-promise' ),
    _                 : require('underscore'),
    url               : require( 'url' ),

    faviconPath       : rootPath + 'front-end/resources/favicon.ico',
    nunjucksPath      : path.join( rootPath, 'front-end/views' ),
    css               : path.join( rootPath, 'front-end/resources/css' ),
    fonts             : path.join( rootPath, 'front-end/resources/fonts' ),
    img               : path.join( rootPath, 'front-end/resources/img' ),
    js                : path.join( rootPath, 'front-end/resources/js' ),
    compiledCss       : path.join( rootPath, 'front-end/.tmp' ),
    bowerComponents   : path.join( rootPath, 'front-end/bower' ),
    commonViews       : path.join( rootPath, 'front-end/views/commons' ),
    uploads           : path.join( rootPath, 'front-end/resources/uploads')
  };
}());
